### ISSUE TITLE
Birth and Death messages via QoS = 0!

### ISSUE THREAD

**Issue by Abdelwadoud-Mabrouk** [eclipse/sparkplug#107]
Can/should Birth and Death messages be sent with Quality of Service 0? I can't read in the specification that this is not intended. But in my opinion, it makes little sense to send state information with a QoS = 0. 
Are there any real applications that use a QoS of 0 for birth and death messages? What is your opinion about this?

**Comment by wes-johnson** [comment]
Sparkplug uses the QoS0 for BIRTH and DEATH messages for a few reasons. This is very much intentional as we don't want messages to show up and some point in the distant future. The NBIRTH and NDEATH messages represent a single MQTT connect/disconnect cycle. Storing and ensuring delivery don't make a lot of sense in this type of situation.

It might be helpful to watch this video where we cover the reasoning: https://www.youtube.com/watch?v=3syYeTg6RBc
