### ISSUE TITLE
Unclear Birth/Death behaviour for Nodes & Devices

### ISSUE THREAD

**Issue by andy1547** [eclipse/sparkplug#117]
I've read over the spec (v2.2 and development) and have some questions about state management. 

**Key themes questions:**

1. Does a NDeath represent the Node being offline, or is it only used to indicate an ungraceful disconnect? 
2. Is the Device's state dependent on the underlying Node state?

**Related workflow questions:**

3. When a Node is disconnecting intentionally (non-persistent connection), should a NDeath be explicitly published before sending an MQTT Disconnect packet to let the Application know the Node is offline? Or should NDeaths never be explicitly published by the Node and only delivered as part of the last will and testament to indicate a ungraceful disconnect?

4. When the Application receives a NDeath packet, should it set the Device metrics to stale? On the event of a ungraceful disconnect where a NDeath is received through the last will and testament, the Device may have technically still been online despite the MQTT connection loss.

5. When a Node is disconnecting intentionally (non-persistent connection), should DDeaths be published if its Devices are still online? From the Node's perspective the Devices are still online after the MQTT connection closes, however the Application may want to consider the Device as being offline (as RBE cannot occur due to the underlying Node being offline).

6. If during a MQTT connection several of the Node's Devices have published DBirths to indicate they are online, and then a ungraceful disconnection occurs, after the Node comes back online does it need to republish DBirths (if from the Node's perspective the Devices have remained online)? The context isn't clear from the line "if this is the first time this device has been seen".

Thanks in advance.

**Comment by jbrzozoski** [comment]
1. NDEATH represents a node being offline, graceful or ungraceful. It is required either way.
2. A device's state is dependent on the associated node. If the parent node sends an NDEATH, all listeners should interpret that as though all associated devices also sent a DDEATH.
3. Yes, when a node disconnects gracefully, it should send a NDEATH first. MQTT brokers will not transmit the LWT NDEATH if the client does a graceful disconnect, but sending the NDEATH is critical for listeners to know when the node is offline.
4. Yes, listening applications should mark all metrics stale when an NDEATH is received for any reason. The "stale" in this case represents that the node is _not actively online_ and there is no guarantee that the values are current.
5. It won't hurt anything if the node publishes DDEATH messages before disconnecting, but it is not required since the NDEATH implies a DDEATH for all associated devices.
6. After any disconnect (NDEATH), all of the node's devices must publish DBIRTHs to indicate they are online.

In general, the concept with Sparkplug is that a node should try to connect to the MQTT broker and then stay connected as much as possible. It is not designed for intermittent connections. 

If a node were to gracefully disconnect w/o sending an NDEATH it breaks many assumptions. If the node failed during the subsequent offline period, then none of the listening applications would know that the node had never returned, and assume that all metrics were still valid and current because of Sparkplug only-report-on-change design goal.

Even with a proper NDEATH announcing each offline event, frequently going offline adds a substantial amount of overhead. The NBIRTH and DBIRTH messages are the biggest payloads in Sparkplug by quite a lot. They have to include the full names of all metrics, while regular NDATA/DDATA include just alias numbers and data for only the metrics that have changed since the last DATA.

**Comment by andy1547** [comment]
Thanks for your quick response, we've updated our implementation, in doing so it's highlighted a case where the Application could remain unaware of the current Node/Device state until a metric value change is RBE.

The v2.1 spec specifies that Application state messages should be published as retained with QOS = 1, however these two parameters aren't specified for subscriptions and other published messages. Moreover, the clean session flag isn't discussed, which if set to false allows messages to delivered to the MQTT client after it comes back online (provided the client had already established a QOS >= 1 subscription and the message being delivered by the MQTT server was QOS >= 1).

It appears this has somewhat been clarified in the dev spec (in both the normative statements and chapter 4) but it's still a little unclear. It seems the direction the spec is going in is to specify non-Application state messages as being published with QOS = 0 + retained false, and setting the clean session flag to true.

This presents an issue when the Application looses comms to the MQTT server, as when it comes back online it's unaware of the current Node/Device state until it receives its first packet for it (either a Birth/Data/Death). Once its received this first packet, it knows the state reliably from then onwards (provided the Application doesn't loose comms again), however RBE means the Application could be potentially waiting forever to receive this packet (if the Node/Device is always online and a metric value change never occurs).

We have tried to over come this by issuing a Rebirth request to each Node/Device every time the Application connects to the MQTT Server to force a Rebirth, however it's not ideal as it moves things towards a poll based approach. In our particular situation the Application is extremely unlikely to loose comms ungracefully (as it's on the same host as the MQTT server), however periodically we take the service which hosts the Application offline to perform maintenance (during which reported Node/Device state changes are missed). Ideally we wouldn't want to issue a Rebirth to Node/Devices on metered connections, it also relies on the Node/Device implementation supporting Rebirths (Node Rebirths are optional in v2.1 but are now compulsory in the dev spec).

The second workaround is to record the timestamp of the last Birth/Data/Death we've received and and flag any Node/Devices that haven't reported any packets for a periodic of time. This can be be aided with a periodic Rebirth request to try and force a Birth packet before they enter the flagging window. This also isn't a perfect solution as it makes the assumption value changes will occur before the flagging period (which is only solved by a periodic Rebirth request if support is implemented in the Node/Device).

I can see others have raised issues related to this suggesting NBirth/NDeath/DBirth/DDeath messages should be published with QOS 1. This is only useful in solving this issue if the Application sets cleanSession false and subscribes with QOS >= 1, although there is an additional corner case when the Application connects for the first time without any session state (or the MQTT server clears the session due to resource constraints). Publishing Births/Deaths with the retained flag helps to overcome that, but would increase the memory consumption of the MQTT server if many Nodes/Devices exist.

So far we've made cleanSession, QOS (publishing & subscriptions), retention behaviour (publishing and discarding retained messages received from subscriptions) configurable in our Application/Nodes/Devices to anticipate any future spec changes, however it would be great to have some clarification on your intended direction with this.

Thanks in advance.

**Comment by wes-johnson** [comment]
I'd suggest looking at the use of 'Primary Host ID' usage in the current version of the spec. It is basically a message to an Edge Node denoting the primary host application is online and therefore a NBIRTH can be sent. This eliminates the need to wait for a message and send a Rebirth request at the host side.

QoS1 and use of clean_session=false introduce a whole host of other potential issues and can not be used.
