### ISSUE TITLE
Expand on required QoS levels for all Sparkplug message types

### ISSUE THREAD

**Issue by nathandavenport** [eclipse/sparkplug#22]
Expand on required QoS levels for all Sparkplug message types. Sparkplug requires that all *BIRTH, *DATA, and *CMD messages must be sent on QoS0.

**Comment by I-Campbell** [comment]
I propose that NDEATH _**MUST**_ be both published as QoS1 and subscribed by the host as QoS1, otherwise Nodes can get stuck ONLINE (when really they are disconnected).
I propose that DDEATH _**MUST**_ be both published as QoS1 and subscribed by the host as QoS1, otherwise Devices can get stuck ONLINE, if there are no other devices publishing on the same edge, and the edge itself does not publish regular NDATA, and the QoS 0 DDEATH is transmitted 0 times.

I propose that the Subscriptions for other topics be allowed to be QoS0 or QoS1, to allow for subscribing to (e.g.) spBv1.0/# at QoS1.  Of course, the MQTT Server will only send as QoS1 those messages which were published as QoS1 to the subscriber, so this has no negative effect on bandwidth whatsoever.

It may be obvious from reading the MQTT spec, but I think it is useful if the sparkplug spec states both the publish and subscribe QoS levels.

**Comment by icraggs-sparkplug** [comment]
When specifying subscription levels, I suggest we say something like "subscribing at least at QoS n".  

You can subscribe at QoS 2, and all the messages will be received at the QoS at which they were sent.  That's the usual MQTT approach in my experience.

**Comment by wes-johnson** [comment]
Based on previous discussions I believe all QoS levels are now properly defined in the develop version of the specification. As noted from previous discussions, Sparkplug is heavily dependent on real time, in-order messages so QoS 1 only makes sense for NDEATH messages and STATE messages. All others will remain at QoS 0 in the spec. Also, we will not use the 'at least' terminology as that shouldn't be done.
