### ISSUE TITLE
Can't pass a single test

### ISSUE THREAD

**Issue by Llorx** [eclipse/sparkplug#282]
I've downloaded the TCK (latest dev version because master version is also not working properly). Compiled it, started the HiveMQ broker with the sparkplug plugin running, and when I connect an Ignition primary host application so I can start my device tests as the first test suggests, it fails with this error:
![image](https://user-images.githubusercontent.com/702490/185937650-06d9bfa8-3a71-4c0b-8da4-83fb68414805.png)

Also when I run the remaining tests, the second and last tests instantly end with a "NOT EXECUTED" message:
![keP0mZNvEs](https://user-images.githubusercontent.com/702490/185941668-4e421f8b-52a7-453d-836f-739fdfed2082.gif)

We want to get listed, but is impossible to have a proper test run right now :-(

If you happen to have a working solution so we can run our tests, we would be really happy to receive one, as we want to continue further in the listing process.

**Comment by icraggs-sparkplug** [comment]
I tried several tests today, and they all worked as well as expected (some tests failed due to spec changes since the ignition implementation). I haven't met your symptom so far.

I found this reference to that message in the HiveMQ support area: https://community.hivemq.com/t/meaning-of-log-messages/145, but I'm not sure how relevant that is. I added the persistence configuration 

What version of HiveMQ CE are you running?  I've run with 2021.2, 2021.3 and today 2022.1. I used the develop branch of Sparkplug today. 

Can you get the Host Application session establishment test to work?

For detailed messages about why the test doesn't start or run, the HiveMQ console should contain them.

**Comment by Llorx** [comment]
The HiveMQ version is the one that automatically downloads when running `gradlew runHivemqWithExtension`, which is the community 2021.1 version.

I'll comment the steps I follow (redoing them from scratch right now just in case I miss something):
1.- I clone the repo: `git clone https://github.com/eclipse/sparkplug.git`.
2.- I go to the sparkplug folder: `cd sparkplug`.
3.- I switch to develop: `git checkout develop`.
4.- Then I go to the tck folder: `cd tck`.
5.- Then I run `gradlew build`.
6.- And after this, I run `gradlew runHivemqWithExtension`.
7.- Then I go to the webconsole folder: `cd webconsole`.
8.- I run `yarn install`.
8.- Then I run the build command: `yarn build`.
9.- And finally I run the start commad: `yarn start`.

With this I have everything running. I then go to http://localhost:300 and connect to the MQTT broker with the default values provided by the application:
![image](https://user-images.githubusercontent.com/702490/186408001-7242adf2-e7f0-4e0e-9eba-4133ed8f6156.png)

And then I fill the edge node data with the test "Session termination test":
![image](https://user-images.githubusercontent.com/702490/186408156-6a00cf54-e5f3-450c-9389-c8918b679449.png)

And when I press Start, it happens what I've shown avobe. It ends suddenly with a "NOT EXECUTED" message. No test ran or whatever :-(

**Comment by icraggs-sparkplug** [comment]
I've put in a PR to report the incorrect parameters to the webconsole: https://github.com/eclipse/sparkplug/pull/285

**Comment by icraggs-sparkplug** [comment]
I think this is done. Thanks.
