### ISSUE TITLE
Add Copyright, Eclipse Foundation Specification License, and Disclaimers to start of spec

### ISSUE THREAD

**Issue by wes-johnson** [eclipse/sparkplug#8]
This is regarding: http://dev.eclipse.org/ipzilla/show_bug.cgi?id=22396

Now that this contribution has been approved, we will need to make an
adjustment to the file headers for the content. It is correct that the
documentation that is produced by this code is licensed under the Eclipse
Foundation Specification License, as noted in the Sparkplug.adoc file; however,
the *code itself* that generates the specification docs is to be licensed under
the EPL-2.0 license as the EFSL applies to the generated documentation only. 

Please review the attachment and ensure that all of the file headers are
showing the EPL-2.0 license as outlined here:

https://www.eclipse.org/projects/tools/documentation.php?id=iot.sparkplug

**Comment by fdesbiens** [comment]
@wes-johnson The Eclipse Foundation recommends using trademark statements in specification documents rather than displaying the (TM) and (R) marks everywhere. It would be best to place such statements in a prominent location at the beginning of the document.

Here is the specific statement that Sharon Macdonald, our trademarks specialist, provided me for use in the Sparkplug specification:

> Sparkplug®, Sparkplug Compatible, and the Sparkplug Logo are trademarks of the Eclipse Foundation.

Sharon also added:
 
> Once Sparkplug Compatible reaches full registration in the United States, the Statement will be updated slightly but for current use this is a proper statement to use.
> 
> In situations where the statement may not work, it is acceptable to use the (TM) and (R) marks on the first appearance of a trademark in the text or on a title or header at the beginning of the text.

I hope this helps. If (R) and (TM) marks are in the document, you can remove them to improve readability.
